version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: GitLab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://sample.example.domain'
        gitlab_rails['time_zone'] = 'Asia/Seoul'
        gitlab_rails['gitlab_email_from'] = 'sample@example.com'
        gitlab_rails['gitlab_email_display_name'] = 'Example name'
        gitlab_rails['gitlab_email_reply_to'] = 'sample.reply@example.com'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "sample@example.com"
        gitlab_rails['smtp_password'] = "sampleEmailPassword"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        # unicorn['port'] = 8080
        # gitlab_workhorse['auth_backend'] = "http://localhost:8080"
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
        logging['logrotate_frequency'] = "weekly"
        logging['logrotate_rotate'] = 52
        logging['logrotate_compress'] = "compress"
        logging['logrotate_method'] = "copytruncate"
        logging['logrotate_delaycompress'] = "delaycompress"
        prometheus_monitoring['enable'] = false
        postgresql['shared_buffers'] = "256MB"
        # Add any other gitlab.rb configuration options if desired
    ports:
      - 'port that user wants:80'
    volumes:
      - ./gitlab_data/conf:/etc/gitlab
      - ./gitlab_data/ssl:/etc/ssl/certs/gitlab
      - ./gitlab_data/logs:/var/log/gitlab
      - ./gitlab_data/main:/var/opt/gitlab

